name: Batch Publish Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'batch-publish/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: batch-publish
    secrets: inherit
