name: Chaos Runner Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'chaos-runner/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: chaos-runner
    secrets: inherit
