name: Chaos Runner Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'chaos-runner/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-pr.yml@main
    with:
      project-dir: chaos-runner
    secrets: inherit
