name: Chaos Runner Release

on:
  push:
    tags: [ 'cr/*' ]

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-release.yml@main
    with:
      project-dir: chaos-runner
    secrets: inherit
