name: Direct Batch Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'direct-batch/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: direct-batch
    secrets: inherit
