name: Direct Batch Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'direct-batch/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-pr.yml@main
    with:
      project-dir: direct-batch
    secrets: inherit
