name: Release Direct Consumer

on:
  push:
    tags: [ 'dc/*' ]

env:
  GODEBUG: x509sha1=1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: "release"
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      GODEBUG: x509sha1=1
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Nats Server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          sudo mv nats-server /usr/local/bin
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v3
      - name: Compile and Test
        run: |
          pushd direct-consumer
          chmod +x gradlew && ./gradlew clean test
          popd
      - name: Verify, Sign and Publish Release
        run: |
          pushd direct-consumer
          ./gradlew -i signArchives signMavenJavaPublication publishToSonatype closeAndReleaseSonatypeStagingRepository
          popd
