name: Encoded KV Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'encoded-kv/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: encoded-kv
    secrets: inherit
