name: Publish Extensions Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'js-publish-extensions/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: js-publish-extensions
    secrets: inherit
