name: Retrier Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'retrier/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-pr.yml@main
    with:
      project-dir: retrier
    secrets: inherit
