name: Retrier Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'retrier/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: retrier
    secrets: inherit
