name: Request Many Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'request-many/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: request-many
    secrets: inherit
