name: Request Many Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'request-many/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-pr.yml@main
    with:
      project-dir: request-many
    secrets: inherit
